# Generated by Django 3.2 on 2021-09-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='Comentario',
            new_name='comentario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('pasajero)', 'Pasajero')], default='pasajero', max_length=50),
        ),
    ]
