# Generated by Django 3.2 on 2021-09-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210906_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributos',
            options={'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='hoteles',
            options={'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Ususarios'},
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='app.hoteles'),
        ),
    ]
