# Generated by Django 3.2 on 2021-09-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210906_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='id_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='app.hoteles'),
        ),
    ]
