# Generated by Django 3.2 on 2021-09-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_hoteles_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteles',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
