# Generated by Django 3.2 on 2021-09-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_hoteles_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='calificacion_comentario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
