# Generated by Django 3.2 on 2021-09-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comentarios_calificacion_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteles',
            name='cant_votos',
            field=models.IntegerField(default=0),
        ),
    ]
