# Generated by Django 3.2.7 on 2021-09-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_hoteles_cant_votos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteles',
            options={'ordering': ['-cant_votos'], 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AddField(
            model_name='hoteles',
            name='url',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
