# Generated by Django 3.2.7 on 2021-09-09 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210908_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteles',
            old_name='url',
            new_name='slug',
        ),
    ]
