# Generated by Django 3.2.7 on 2021-09-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_url_hoteles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteles',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
