# Generated by Django 3.2.7 on 2021-09-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
